FROM python:3.10.6
WORKDIR /app
COPY ./backend/ .
COPY ./poetry.lock .
COPY ./pyproject.toml .
ENV PYTHONPATH "${PYTHONPATH}:/"
RUN pip install "poetry==1.5.1"
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root
RUN chmod +x ./backend_entrypoint.sh