# Generated by Django 3.2.20 on 2023-07-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
                ('link', models.CharField(blank=True, max_length=1024, verbose_name='Ссылка')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('discount', models.IntegerField(blank=True, verbose_name='Скидка')),
                ('rating', models.FloatField(blank=True, verbose_name='Рейтинг')),
                ('image', models.CharField(blank=True, max_length=1024, verbose_name='Картинка')),
            ],
        ),
    ]
