FROM python:3.10.6
WORKDIR /bot
COPY ./bot .
COPY ./poetry.lock .
COPY ./pyproject.toml .
RUN pip install "poetry==1.5.1"
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root
ENV PYTHONPATH "${PYTHONPATH}:/"
CMD ["python", "main.py"]